/**
 * Local development uses SQLite, production uses Postgres.
 *
 * Prisma will not accept an env var for the datasource provider, so rather than
 * editing schema.prisma by hand (and risking that edit reaching production and
 * breaking the deploy — which is exactly what happened once), this generates
 * prisma/schema.local.prisma from the real schema with the provider swapped.
 *
 *   npm run db:local     → write the local schema, push it, generate the client
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, 'schema.prisma');
const target = join(here, 'schema.local.prisma');

const schema = readFileSync(source, 'utf8');
if (!/provider\s*=\s*"postgresql"/.test(schema)) {
  console.error('schema.prisma is not on postgresql — production expects it to be. Not overwriting.');
  process.exit(1);
}

writeFileSync(
  target,
  '// GENERATED by prisma/local-schema.mjs — do not edit, do not commit.\n' +
  '// Local SQLite mirror of schema.prisma. Edit schema.prisma instead.\n' +
  schema.replace(/provider\s*=\s*"postgresql"/, 'provider = "sqlite"'),
);

console.log('wrote', target, '(sqlite)');
